In [2]:
import pandas as pd
from frust.stepper import Stepper

In [13]:
df = pd.read_parquet("ani-ligands.parquet")
df

,ligand_name,rpos,atoms,moltype,coords_embedded,xtb-gfnff-opt-electronic_energy,xtb-gfnff-opt-normal_termination,xtb-gfnff-opt-opt_coords,xtb-gfn-electronic_energy,xtb-gfn-normal_termination,xtb-gfn-opt-electronic_energy,xtb-gfn-opt-normal_termination,xtb-gfn-opt-opt_coords
2,CC(C)(C)CC(NC1=CC=CC(Cl)=C1)=O,None,"[C, C, C, C, C, C, N, C, C, C, C, C, Cl, C, O,...",anichl,"[[-3.892263831103961, 0.36162644226243174, -0....",-5.422209,True,"[[-3.88854996600144, 0.14703385812457, -0.7063...",-45.421153,True,-45.426252,True,"[[-3.74527574632423, -0.01853303029875, -0.799..."
5,CC(NC1=CC=C(C#N)C=C1)=O,None,"[C, C, N, C, C, C, C, C, N, C, C, O, H, H, H, ...",anin,"[[3.7655908621441436, 0.25966799096066845, -0....",-4.185910,True,"[[3.73583965795299, 0.41988015416469, -0.23507...",-33.226314,True,-33.230918,True,"[[3.71300047139607, 0.45652088507515, -0.11554..."

In [ ]:
step = Stepper("MOLS", save_output_dir=False)
df = step.xtb(df, "NOOB0", {"gfn": 2, "sp": None}, n_cores=1)
df = step.orca(df, "nab", {"HF": None, "STO-3G": None})
df

2026-04-22 20:08:50 INFO  frust.stepper.MOLS.job1111: Working dir: .
2026-04-22 20:08:50 INFO  frust.stepper.MOLS.job1111: [NOOB0-gfn] row 2 (CC(C)(C)CC(NC1=CC=CC(Cl)=C1)=O)…
2026-04-22 20:08:50 INFO  frust.stepper.MOLS.job1111: [NOOB0-gfn] row 5 (CC(NC1=CC=C(C#N)C=C1)=O)…
2026-04-22 20:08:50 INFO  frust.stepper.MOLS.job1111: [nab-HF-STO-3G] row 2 (CC(C)(C)CC(NC1=CC=CC(Cl)=C1)=O)…
2026-04-22 20:08:54 INFO  frust.stepper.MOLS.job1111: [nab-HF-STO-3G] row 5 (CC(NC1=CC=C(C#N)C=C1)=O)…

,ligand_name,rpos,atoms,moltype,coords_embedded,xtb-gfnff-opt-electronic_energy,xtb-gfnff-opt-normal_termination,xtb-gfnff-opt-opt_coords,xtb-gfn-electronic_energy,xtb-gfn-normal_termination,xtb-gfn-opt-electronic_energy,xtb-gfn-opt-normal_termination,xtb-gfn-opt-opt_coords,NOOB0-gfn-electronic_energy,NOOB0-gfn-normal_termination,nab-HF-STO-3G-electronic_energy,nab-HF-STO-3G-normal_termination
2,CC(C)(C)CC(NC1=CC=CC(Cl)=C1)=O,None,"[C, C, C, C, C, C, N, C, C, C, C, C, Cl, C, O,...",anichl,"[[-3.892263831103961, 0.36162644226243174, -0....",-5.422209,True,"[[-3.88854996600144, 0.14703385812457, -0.7063...",-45.421153,True,-45.426252,True,"[[-3.74527574632423, -0.01853303029875, -0.799...",-45.426252,True,-1040.351641,True
5,CC(NC1=CC=C(C#N)C=C1)=O,None,"[C, C, N, C, C, C, C, C, N, C, C, O, H, H, H, ...",anin,"[[3.7655908621441436, 0.25966799096066845, -0....",-4.185910,True,"[[3.73583965795299, 0.41988015416469, -0.23507...",-33.226314,True,-33.230918,True,"[[3.71300047139607, 0.45652088507515, -0.11554...",-33.230918,True,-522.586235,True